version: '3.8'

services:
  frpc:
    image: snowdreamtech/frps:nightly-trixie
    container_name: frps
    restart: always
    network_mode: host
    volumes:
      - [your shit here]:/etc/frp/frps.toml
